name = "Allen Hsieh"
avatar = "images/icon.gif" # Avatar image. Default to "images/profile.webp".
bio = "Backend Engineer"
company = "Yahoo!"
location = "Taiwan"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"
