baseURL = "https://allen-hsieh1992.github.io/"
title = "艾倫的開發心路歷程"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © 2021-{year} Allen Hsieh. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "zh-tw"
#defaultContentLanguageInSubdir = false # If you use only one language comment this option
#disableLanguages = ["fr", "zh-cn" ,"zh-tw"] # For disable one or more language

# Pagination
paginate = 5
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true

hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "JSON"]
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
